version: '3.8'

services:
  postgres:
    platform: linux/amd64
    image: postgis/postgis:16-3.4
    container_name: rentoss-postgres
    environment:
      POSTGRES_DB: rentoss
      POSTGRES_USER: rentoss
      POSTGRES_PASSWORD: rentoss123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql

  redis:
    platform: linux/amd64
    image: redis:7-alpine
    container_name: rentoss-redis
    ports:
      - "6379:6379"

  zookeeper:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: rentoss-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    platform: linux/amd64
    image: confluentinc/cp-kafka:7.5.0
    container_name: rentoss-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data:
